import type { ResourceConfig } from "./field-types";
import { PROJECT_SECTORS, EMIRATES, SCOPE_TAGS } from "@/lib/constants";

const seoFields = [
  { name: "seo.title", label: "SEO Title", type: "text" as const, help: "Falls back to the site default when empty" },
  { name: "seo.description", label: "SEO Description", type: "textarea" as const },
  { name: "seo.noindex", label: "Hide from search engines (noindex)", type: "boolean" as const },
];

export const RESOURCE_CONFIGS: Record<string, ResourceConfig> = {
  posts: {
    key: "posts",
    label: "Blog Posts",
    description: "Articles for the blog. Drafts stay hidden until you publish them.",
    apiPath: "/api/posts",
    searchable: true,
    columns: [
      { key: "title", label: "Title" },
      { key: "status", label: "Status" },
      { key: "publishedAt", label: "Published" },
    ],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "excerpt", label: "Excerpt", type: "textarea", required: true },
      { name: "body", label: "Body", type: "richtext" },
      { name: "coverImage", label: "Cover Image", type: "image" },
      { name: "status", label: "Status", type: "select", options: ["draft", "published"] },
      ...seoFields,
    ],
  },
  categories: {
    key: "categories",
    label: "Categories",
    description: "Group blog posts into topics. Each one gets its own archive page.",
    apiPath: "/api/categories",
    searchable: true,
    columns: [{ key: "name", label: "Name" }, { key: "slug", label: "Slug" }],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  tags: {
    key: "tags",
    label: "Tags",
    description: "Finer-grained labels for blog posts.",
    apiPath: "/api/tags",
    searchable: true,
    columns: [{ key: "name", label: "Name" }, { key: "slug", label: "Slug" }],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
    ],
  },
  pages: {
    key: "pages",
    label: "Pages",
    description: "Home, About Us, AMC and other standard pages, built from reorderable sections.",
    apiPath: "/api/pages",
    searchable: true,
    columns: [{ key: "title", label: "Title" }, { key: "slug", label: "Slug" }, { key: "status", label: "Status" }],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true, help: "\"about-us\", \"home\", \"amc\", \"careers\"" },
      { name: "blocks", label: "Page Content", type: "blocks" },
      { name: "status", label: "Status", type: "select", options: ["draft", "published"] },
      ...seoFields,
    ],
  },
  services: {
    key: "services",
    label: "Services",
    description: "The service pages, shown in the services grid and in navigation.",
    apiPath: "/api/services",
    searchable: true,
    columns: [{ key: "title", label: "Title" }, { key: "order", label: "Order" }, { key: "status", label: "Status" }],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "summary", label: "Summary (for service cards)", type: "textarea", required: true },
      { name: "coverImage", label: "Cover Image", type: "image" },
      { name: "blocks", label: "Page Content", type: "blocks" },
      { name: "order", label: "Display Order", type: "number", defaultValue: 0 },
      { name: "status", label: "Status", type: "select", options: ["draft", "published"] },
      ...seoFields,
    ],
  },
  projects: {
    key: "projects",
    label: "Projects",
    description: "Completed work — client, sector, photos and results.",
    apiPath: "/api/projects",
    searchable: true,
    columns: [{ key: "title", label: "Title" }, { key: "client", label: "Client" }, { key: "sector", label: "Sector" }],
    fields: [
      { name: "title", label: "Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "client", label: "Client name", type: "text", required: true },
      { name: "clientLogo", label: "Client Logo", type: "image" },
      { name: "sector", label: "Sector", type: "select", options: PROJECT_SECTORS, required: true },
      { name: "emirate", label: "Emirate", type: "select", options: EMIRATES, required: true },
      { name: "area", label: "Area", type: "text", help: "e.g. \"Deira\" — feeds local SEO" },
      { name: "year", label: "Year", type: "number", required: true },
      { name: "status", label: "Project Status", type: "select", options: ["Completed", "Ongoing"] },
      { name: "scopeOfWork", label: "Scope of Work", type: "multiselect", options: SCOPE_TAGS },
      { name: "summary", label: "Summary", type: "textarea", required: true },
      { name: "body", label: "Full Story (challenge / solution / outcome)", type: "richtext" },
      { name: "coverImage", label: "Cover Image", type: "image", required: true },
      { name: "gallery", label: "Gallery", type: "imageArray" },
      { name: "stats", label: "Stats (e.g. \"480 detectors\")", type: "statsArray" },
      { name: "featured", label: "Featured on homepage", type: "boolean" },
      { name: "order", label: "Display Order", type: "number", defaultValue: 0 },
      { name: "publishStatus", label: "Status", type: "select", options: ["draft", "published"] },
      ...seoFields,
    ],
  },
  jobs: {
    key: "jobs",
    label: "Careers",
    description: "Open positions listed on the careers page.",
    apiPath: "/api/jobs",
    searchable: true,
    columns: [{ key: "title", label: "Title" }, { key: "department", label: "Department" }, { key: "status", label: "Status" }],
    fields: [
      { name: "title", label: "Job Title", type: "text", required: true },
      { name: "slug", label: "Slug", type: "slug", required: true },
      { name: "department", label: "Department", type: "text", required: true },
      { name: "location", label: "Location", type: "text", defaultValue: "Dubai, UAE" },
      { name: "employmentType", label: "Employment Type", type: "select", options: ["Full-time", "Part-time", "Contract"] },
      { name: "description", label: "Description", type: "richtext" },
      { name: "requirements", label: "Requirements", type: "stringArray" },
      { name: "status", label: "Status", type: "select", options: ["draft", "published"] },
      ...seoFields,
    ],
  },
  redirects: {
    key: "redirects",
    label: "Redirects",
    description: "Send old URLs to new ones so existing links and search rankings survive.",
    apiPath: "/api/redirects",
    searchable: true,
    columns: [{ key: "from", label: "From" }, { key: "to", label: "To" }, { key: "hits", label: "Hits" }],
    fields: [
      { name: "from", label: "From path", type: "text", required: true, help: "e.g. /blog/old-post.html" },
      { name: "to", label: "To (path or full URL)", type: "text", required: true },
      { name: "statusCode", label: "Status Code", type: "select", options: ["301", "302"] },
    ],
  },
  media: {
    key: "media",
    label: "Media Library",
    description: "Manage uploaded images, logos, diagrams, and assets.",
    apiPath: "/api/media",
    searchable: true,
    columns: [
      { key: "url", label: "Thumbnail" },
      { key: "alt", label: "Alt Text" },
      { key: "storage", label: "Storage" },
      { key: "createdAt", label: "Uploaded" },
    ],
    fields: [
      { name: "alt", label: "Alt Text", type: "text", required: true },
    ],
  },
};

export function getResourceConfig(key: string): ResourceConfig | undefined {
  return RESOURCE_CONFIGS[key];
}
